os: Visual Studio 2015
platform:
  - x64
  - x86
install:
  - ps: Install-Product node "" $env:platform # install deps under latest runtime (source-only deps will switch cleanly for tests)
  - npm install -g npm-add-script
  - npmAddScript -f -k install -v "" # Disable the normal install script of this module
  - npm install # Install just dependencies
build_script:
  - .\node_modules\.bin\node-pre-gyp clean # make sure we start clean
  - node build_matrix.js
  - for /f "usebackq" %%v in (`node -e "console.log(JSON.parse(require ('fs').readFileSync('package.json')).version)"`) do set SEMVER=%%v # make the semver available for the deploy step
artifacts:
  - path: 'build\stage\*\*.tar.gz'
test: OFF
deploy:
  provider: GitHub
  tag: $(SEMVER)
  description: $(APPVEYOR_PROJECT_NAME) $(SEMVER)
  auth_token:
    secure: gkLVM16ULpFG6pKrcHVJfkyrl+ZBUJFZUto6lBuTd7FkyUlOyHE6KilyIWzsseNc
  artifact: /.*/
  draft: true
  overwrite: true
  on:
    branch: node-pre-gyp
