language: cpp
sudo: false
env:
  global: NVM_PRE="7.7.3 6.10.0 5.12.0 4.8.0 0.12.17"
matrix:
  include:
    - os: linux
      dist: trusty
      env: NVM_OS=linux NVM_ARCH=x64
      addons:
        apt:
          packages:
            # for robot to build
            - libxinerama-dev
            - libxtst-dev
            # for electron to run
            - libgtk2.0-0
            - libx11-xcb1
            - libxss1
            - libudev1
            - libgconf-2-4
            - libnss3
            - libasound2
    - os: linux
      dist: trusty
      env: NVM_OS=linux NVM_ARCH=x86
      addons:
        apt:
          packages:
            # for robot to build
            - g++-multilib
            - libxinerama-dev:i386
            - libxtst-dev:i386
            # for electron to run
            - libgtk2.0-0:i386
            - libx11-xcb1:i386
            - libxss1:i386
            - libudev1:i386
            - libgconf-2-4:i386
            - libnss3:i386
            - libasound2:i386
    - os: osx
      env: NVM_OS=darwin NVM_ARCH=x64
cache:
  directories:
    - node_versions
install:
  - | # Replace nvm with a fresh copy and pre-load with arch-specific binaries
    mkdir -p $HOME/node_versions
    rm -rf $HOME/.nvm
    mkdir -p $HOME/.nvm/versions
    mv $HOME/node_versions $HOME/.nvm/versions/node
    curl -s https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh -o $HOME/.nvm/nvm.sh
    curl -s https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm-exec -o $HOME/.nvm/nvm-exec
    chmod 755 $HOME/.nvm/nvm-exec
    for ver in $NVM_PRE; do
      dir=$HOME/.nvm/versions/node/v$ver
      if [ ! -e $dir ]; then
        mkdir -p $dir
        curl -s https://nodejs.org/dist/v$ver/node-v$ver-$NVM_OS-$NVM_ARCH.tar.gz \
          | tar -xzC$dir --strip-components=1
      fi
    done
  - nvm ls
  - nvm use 7.7.3 # start using one of the arch-specific versions
  - npm install -g npm-add-script
  - npmAddScript -f -k install -v "" # Disable the normal install script of this module
  - npm install # Install just dependencies
script:
  - ./node_modules/.bin/node-pre-gyp clean # make sure we start clean
  - node build_matrix.js
before_cache:
  - mv $HOME/.nvm/versions/node $HOME/node_versions
deploy:
  provider: releases
  skip_cleanup: true
  tag_name: 1.0.3
  api_key:
    secure: "Fu+1ozrzYxdU4DNjXR8x/7RSZnbJiNqItFIYCK0uBwfKfFOtAsCUbL4M8KXtbUL43f+N9OsRSOHoRDUoNJuTSa+ACQCcMgaWZFWpB9IerimBrfHgP/Bge8OxiB3b3L43PppWgvwIeywOIj8WZoVuVAGNnDreWT/8N3bqPamNvHWtWbWUFcA+zjgkRbuCAiuYzGwhnZ97sd/D7jMcYX9nA74hkF+gt4x8cHgBAYu/VrtCX9akArJG+8zlRROBK49fPx9hwe5y6X9TOIz9bFXqoJS2z9LoZLgXhNtg+LLw6uQ8akFDFA05I094wtnwrY4Ihz4S8FFYSE8/B4W/V5ZdWqgdHy4tqU2ZfWiRjtGL0P8vZlIJ/yIKGY7D91TwcZAh3n09hTUMYi/weCB6Xbma69OMh01QDjvSorBlAImEFNPymER4JYqGhBmF9gHlOm1kgRp4DRrMiuSfIdM9aTvThY915D62NKRCrZ4MiMyfS6d1POBsz/TWvJW8OIhIDQrVbjmmV9Wr8r9TkMLOTucrHVuK+ZcH1NETiBaMbXZ4+0Y8DHxMFG1kkS6u52d08XXftmG27Ui9yKoGmezPWhlpOLIWTthI0C7MWHYbpYKIhf70A/cJ96DcXT8XQgebrGH/fFMgT6Jb6kSXoSbo8L2+dyINdu6YjvG84AmOD8osffs="
  file_glob: true
  file: build/stage/*/*.tar.gz
  draft: true
  overwrite: true
  on:
    branches: prebuilt
